### ISSUE TITLE
Изменить название на ScumYablochki

### ISSUE THREAD

**Issue by L3odr0id** [NeoD1m/SkamYablochki#1]
Предлагаю изменить название репозитория на S**cum**Yablochki

**Comment by NeoD1m** [comment]
Предлагаю изменить название репозитория на sCUMYablochki

**Comment by PliantSoup** [comment]
Предлагаю забанить L3odr0id

**Comment by L3odr0id** [comment]
Отклоняю предложение Супа

**Comment by NeoD1m** [comment]
Авторы не пришли к согласию
